export const routes = [
  "/",
  "/blog",
  "/blog/how-to-choose-nursing-career-path",
  "/blog/how-to-use-pyqs-effectively",
  "/blog/norcet-vs-rrb-which-exam-to-target",
  "/courses",
  "/exams",
  "/exams/aiims-norcet",
  "/exams/bihar-cho-btsc",
  "/exams/dsssb-nursing-officer",
  "/exams/esic-nursing-officer",
  "/exams/hssc-staff-nurse",
  "/exams/kerala-psc-staff-nurse",
  "/exams/mp-nhm-staff-nurse",
  "/exams/osssc-nursing-officer",
  "/exams/rajasthan-cho",
  "/exams/rrb-staff-nurse",
  "/exams/up-nhm-cho",
  "/mock-tests",
  "/practice",
  "/pyqs",
  "/roadmaps",
  "/roadmaps/30-day-norcet-plan",
  "/roadmaps/working-nurse-study-plan",
  "/subject-wise-tests"
] as const;
