export const routes = [
  '/',
  '/how-to-become-a-nurse',
  '/nursing-career-options',
  '/scope-of-nursing-in-india',
  '/career-after-bsc-nursing',
  '/bsc-nursing-vs-gnm',
  '/anm-vs-gnm',
  '/bsc-nursing-course-details',
  '/gnm-nursing-course-details',
  '/skills-required-for-nurse',
  '/role-of-nurse-in-hospital',
  '/types-of-nursing-jobs',
  '/government-jobs-after-nursing',
  '/private-jobs-after-nursing',
  '/abroad-opportunities-for-nurses',
  '/nursing-career-salary',
  '/future-scope-of-nursing',
] as const;
